// stdlib
#include <assert.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <errno.h>
// system
#include <fcntl.h>
#include <poll.h>
#include <unistd.h>
#include <arpa/inet.h>
#include <sys/socket.h>
#include <netinet/ip.h>
// C++
#include <vector>

typedef struct pollfd pollfdl;


static void msg(const char *msg) {
  fprintf(stderr, "%s\n", msg);
}

static void die(const char *msg) {
  int err = errno;
  fprintf(stderr, "[%d] %s\n", err, msg);
  abort();
}

static void fd_set_nb(int fd) {
    errno = 0;
    int flags = fcntl(fd, F_GETFL, 0);
    if (errno) {
        die("fcntl error");
        return;
    }

    flags |= O_NONBLOCK;

    errno = 0;
    (void)fcntl(fd, F_SETFL, flags);
    if (errno) {
        die("fcntl error");
    }
}

const size_t k_max_msg = 32 << 20;

typedef struct Conn {
  int fd = -1;
  // application's intention, for event loop
  bool want_read = false;
  bool want_write = false;
  bool want_close = false;
  // buffered input and output
  std::vector<uint8_t> incoming; // data to be parsed by the application
  std::vector<uint8_t> outgoing; // responses generated by the application
} Conn;


static int32_t write_all(int fd, const char *buf, size_t n) {
  while( n > 0 ) {
    ssize_t rv = write(fd, buf, n);
    if (rv <= 0) {
      return -1;
    }
    assert((size_t) rv <= n);
    n -= (size_t) rv;
    buf += rv;
  }

  return 0;
}


static int32_t one_reques(int connfd) {
  char rbuf[4 + k_max_msg];
  errno = 0;
  int32_t err = read_full(connfd, rbuf, 4);
  if (err) {
    msg(errno == 0 ? "EOF" : "read() error");
    return err;
  }

  uint32_t len = 0;

  memcpy(&len, rbuf, 4);
  if(len > k_max_msg) {
    msg("too long");
    return -1;
  }
  
  err = read_full(connfd, &rbuf[4], len);
  if(err) {
    msg("read() error");
    return err;
  }
  printf("client says: %.*s\n", len, &rbuf[4]);
  
  const char reply[] = "world";
  char wbuf[4 + sizeof(reply)];
  len = (uint32_t) strlen(reply);
  memcpy(wbuf, &len, 4);
  memcpy(&wbuf[4], reply, len);
  return write_all(connfd, wbuf, 4 + len);
}

int main() {
  // obtain socket handle
  int fd = socket(AF_INET, SOCK_STREAM, 0);
  if(fd < 0){
    die("socket()");
  } 
  
  /* Set the socket options
   * reference: https://stackoverflow.com/a/3233022https://stackoverflow.com/a/3233022
   */
  int val = 1;
  setsockopt(fd, SOL_SOCKET, SO_REUSEADDR, &val, sizeof(val));

  struct sockaddr_in addr = {};
  addr.sin_family = AF_INET;
  addr.sin_port = htons(1234);          // port
  addr.sin_addr.s_addr = htonl(0);      // wildcard IP (0.0.0.0)
  int rv = bind(fd, (const struct sockaddr *)&addr, sizeof(addr));
  if (rv) {
    die("bind()");
  }

  fd_set_nb(fd);

  rv = listen(fd, SOMAXCONN);
  if(rv) { die ("listen()"); }

  // a map of all client connections, keyed by fd
  std::vector<Conn *> fd2conn;
  // the event loop
  std::vector<pollfd> poll_args;
  while(true) {
    // prepare the arguments of poll()
    poll_args.clear();
    // put the listening sockets in the first position
    pollfd pfd = {fd, POLLIN, 0};
    poll_args.push_back(pfd);
    // the rest are connections sockets
    for (Conn *conn : fd2conn) {
      if(!conn) { continue; }
      // always poll() for error
      pollfd pfd = {conn->fd, POLLERR, 0};
      if (conn->want_read) {
        pfd.events |= POLLIN;
      }
      if(conn->want_write) {
        pfd.events |= POLLOUT;
      }
      poll_args.push_back(pfd);
    }
    // wait for readiness


  }

  return 0;

}
